name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Bump version and tag commit
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          default_bump: false
          custom_release_rules: deprecate:minor:Deprecated,feat:minor:Added,fix:patch:Fixed,performance:patch:Performance,remove:major:Removed,security:patch:Security
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        if: ${{ steps.tag_version.outputs.new_tag != null }}
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
