name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  first:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Verify title
        uses: amannn/action-semantic-pull-request@v4.5.0
        with:
          types: |
            build # ignore
            chore/release # ignore ???
            deprecate # minor (must add feature with it); Deprecated
            devops # ignore
            documentation # ignore
            feature # minor; Added
            fix # patch; Fixed
            performance # patch; Performance
            refactor # ignore
            remove # major; Removed
            security # patch; Security
            style # ignore
            testing # ignore
          disallowScopes: |
            release
          subjectPattern: ^[^A-Z].*[^.]$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character or end with a '.'.
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
